name: Test

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Run Unit Tests
        run: go test -p 1 ./... -tags=unit -v

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down

  e2e-test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      DB_NAME: shop
      DB_USER: bernie
      DB_PASS: 1234
      DB_HOST: localhost
      DB_PORT: 3308
      GRPC_PORT: 3333

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Run E2E Tests
        run: go test -p 1 ./... -tags=e2e -v

      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down